#Author:        TGhelere
#Github:        https://github.com/tghelere
#Project Repo:  git@github.com:tghelere/wswd.git

version: '3.1'

services:
    adminer:
        image: adminer:latest
        ports:
            - "8080:8080"

    db:
        image: mariadb:latest
        volumes:
            - paulaayresferreira:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    wordpress:
        # image: wordpress:latest 
        build: ./
        volumes:
            - ./wp-content:/var/www/html/wp-content
        ports:
            - 80:80

volumes:
    paulaayresferreira:
